### ISSUE TITLE
Optional dependencies page outdated

### ISSUE THREAD

**Issue by benhinssen** [jcabi/jcabi-http#100]
I noticed that the optional dependencies page is not up to date: http://http.jcabi.com/optional-dependencies.html

When I include `jersey-core` 1.19, I still get an exception when using the `uri()` method.
```
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:122)
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:91)
	at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:69)
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:80)
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:99)
	at com.jcabi.http.request.BaseRequest$BaseURI.path(BaseRequest.java:442)
```

If I would include `jersey-client` 1.19, it does work.
```
<dependency>
     <groupId>com.sun.jersey</groupId>
    <artifactId>jersey-client</artifactId>
     <version>1.19</version>
</dependency>
```

**Comment by dmarkov** [comment]
@rultor rultor closed it by mistake, @benhinssen please take a look

**Comment by benhinssen** [comment]
@dmarkov In the master branch this looks ok now.  On the [site](http://http.jcabi.com/optional-dependencies.html) it still shows the previous outdated dependency.

**Comment by yegor256** [comment]
@rultor release, tag is `1.14.1`

**Comment by yegor256** [comment]
@rultor release, tag is `1.14.1`

**Comment by yegor256** [comment]
@rultor release, tag is `1.14.1`

**Comment by yegor256** [comment]
@benhinssen please take a look, should be OK now. Please close the ticket if done. Thanks.

**Comment by benhinssen** [comment]
@yegor256 Looks ok!
