### ISSUE TITLE
Add method `Request#headers(Iterable<String>)`

### ISSUE THREAD

**Issue by pinaf** [jcabi/jcabi-http#106]
Request could use a method `Request headers(Iterable<String>)` that takes multiple headers at once. This would make it easier to easily convert the headers of `Takes` request to a jcabi-http Request.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@pinaf even though it may sound like a good idea, I'm against "universal" interfaces, which have too many methods to satisfy all possible needs. So, my answer is "no", but thanks for the suggestion )
