### ISSUE TITLE
Travis CI is not configured for container-based infrastructure

### ISSUE THREAD

**Issue by pinaf** [jcabi/jcabi-http#108]
Travis CI introduced a new container-based infrastructure which is a lot faster.
Let's change `.travis.yaml` according to these [instructions](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade)

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@pinaf I tried to use it a few months ago, without any good results... there were some problems with Ruby, if I remember it right. anyway, it works fine as it is, why changing?

**Comment by pinaf** [comment]
@yegor256 I'd say speed and also they'll probably disable the legacy infrastructure sometime.

**Comment by pinaf** [comment]
@yegor256 what do you think?

**Comment by yegor256** [comment]
@pinaf let's try: f886a00

**Comment by yegor256** [comment]
@pinaf seems to be working fine, thanks
