### ISSUE TITLE
Please add an example of how to use assertHeader() with the Matcher

### ISSUE THREAD

**Issue by alxn** [jcabi/jcabi-http#109]
It would be great to see an example of [`.assertHeader(String, Matcher<Iterable<String>>)`](http://http.jcabi.com/apidocs-1.8.2/com/jcabi/http/response/RestResponse.html#assertHeader%28java.lang.String,%20org.hamcrest.Matcher%29).

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@alxn how about this: 3b99dad

**Comment by yegor256** [comment]
@alxn oops, my bad: b230d76

**Comment by yegor256** [comment]
@alxn even bigger example: 5ccd57d

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#109` is not assigned, can't get performer
