### ISSUE TITLE
android gradle issue

### ISSUE THREAD

**Issue by daneshkohan** [jcabi/jcabi-http#111]
Hi there,
I get error through android gradle with the follwoing script:
compile 'com.jcabi:jcabi-http:1.10.4'
error is: Error:Failed to notify project evaluation listener.

Do you know, how to solve this issue?

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@daneshkohan can you tell me how to reproduce this error? what exactly do you do?

**Comment by petarmitrovic** [comment]
I'm facing the same issue - just added following line to the dependencies block within my Gradle build file:
`compile 'com.jcabi:jcabi-http:1.16'`

**Comment by andreoss** [comment]
@petarmitrovic @daneshkohan 
I was unable to verify this bug with Gradle 6.1.1 and Android SDK 29, with this config (also checked 1.10.4 and 1.16)
```
apply plugin: 'com.android.application'
android { compileSdkVersion 29 }
repositories { jcenter() }
dependencies { implementation 'com.jcabi:jcabi-http:1.17.3' }
```
Feel free to re-open, if the error occurs again. It would be nice to have `build.gradle` and output of `gradle clean build --stacktrace` in this case.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#111` is not assigned, can't get performer
