### ISSUE TITLE
MkQuery should have method to return body bytes

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-http#113]
To retrieve String body using `MkQuery` one can use `body()` method, but there is no method to retrieve binary data, so it is impossible to test handling of non-text content.
Please add a method that would return `byte[]` of the body, without any transcoding.

**Comment by longtimeago** [comment]
@yegor256 can we dispatch the issue?

**Comment by dmarkov** [comment]
@krzyk we will find someone to do this task, soon

**Comment by dmarkov** [comment]
@krzyk thanks for the report, I topped your acc for 15 mins, payment ID `66328266`

**Comment by longtimeago** [comment]
@dmarkov please, give it to me. I have a fix

**Comment by longtimeago** [comment]
@dmarkov here is the fix https://github.com/jcabi/jcabi-http/pull/114

**Comment by yegor256** [comment]
@rultor release, tag is `1.13`

**Comment by longtimeago** [comment]
@yegor256 cool, thanks!

**Comment by longtimeago** [comment]
@krzyk please, close the issue

**Comment by krzyk** [comment]
@longtimeago great, thanks

**Comment by dmarkov** [comment]
> @dmarkov please, give it to me. I have a fix

@longtimeago @yegor256 any objections?

**Comment by dmarkov** [comment]
> @dmarkov here is the fix https://github.com/jcabi/jcabi-http/pull/114

@longtimeago OK thanks
