### ISSUE TITLE
LastModifiedCachingWire.java:141-142: Evict cache entry if If-Modified-Since...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-http#120]
Puzzle `90-f5d7f05d` in `src/main/java/com/jcabi/http/wire/LastModifiedCachingWire.java:141-142` has to be resolved: Evict cache entry if If-Modified-Since request responded with HTTP_OK code and no Last-Modified header.... The puzzle was created by Igor Piddubnyi on 15-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

<hr id='w'>

**Comment by dmarkov** [comment]
@rajithd could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by cvrebert** [comment]
Basically, if the new lacks a `Last-Modified` header, implying it's not cacheable, then there's no point in keeping the old response (which is outdated) in the cache. (And obviously the new response can't be cached since it lacks the required header.)

**Comment by dmarkov** [comment]
@rajithd the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; as a reminder, don't forget to remove the `@todo` puzzle from the source code; -30 added to your rating, current score is: [-120](http://www.netbout.com/b/36278?open=rating)

**Comment by dmarkov** [comment]
@westonized can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by westonized** [comment]
@dmarkov The work is done and reviewed, can you follow this up for closure please? PR #134

**Comment by dmarkov** [comment]
> @dmarkov The work is done and reviewed, can you follow this up for closure please? PR #134 

@westonized PR is still open. once it's merged, we'll close this ticket

**Comment by westonized** [comment]
@dmarkov I know, it's waiting on yegor, 10 days now, is this normal? Has nobody else got any authority to merge?

**Comment by dmarkov** [comment]
> @dmarkov I know, it's waiting on yegor, 10 days now, is this normal? Has nobody else got any authority to merge? Aside from not gettting paid, I've got 2 task limit and both are waiting on yegor like this.
> 

@westonized @yegor256 could you please help us here?

**Comment by westonized** [comment]
@dmarkov PR's merged so can this get closed and I get paid?

**Comment by dmarkov** [comment]
@yegor256 2 puzzles were created here: `120-e6bf947f`/#139, `120-2756c8f7`

**Comment by dmarkov** [comment]
@yegor256 Done, the task is closed

**Comment by dmarkov** [comment]
@westonized thank you, added **30 mins** to your acc, payment num is `AP-8M112932NC376593R`, 839 hours and 48 mins spent in total to complete... +30 added to your rating, current score is: [+45](http://www.netbout.com/b/37035?open=rating)

**Comment by 0pdd** [comment]
@dmarkov 2 puzzles [#334](https://github.com/jcabi/jcabi-http/issues/334), [#335](https://github.com/jcabi/jcabi-http/issues/335) are still not solved.

**Comment by 0pdd** [comment]
@dmarkov 2 puzzles [#unknown](), [#unknown]() are still not solved; solved: [#334](https://github.com/jcabi/jcabi-http/issues/334), [#335](https://github.com/jcabi/jcabi-http/issues/335).
