### ISSUE TITLE
LastModifiedCachingWire.java:46-47: If the original request already...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-http#121]
Puzzle `90-35dd830e` in `src/main/java/com/jcabi/http/wire/LastModifiedCachingWire.java:46-47` has to be resolved: If the original request already has an If-Modified-Since header it should be sent directly.... The puzzle was created by Igor Piddubnyi on 15-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmarkov** [comment]
@amihaiemil it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket; Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by cvrebert** [comment]
After the refactoring that was done in other tickets after the puzzle was created, the change should now be applied to `AbstractHeaderBasedCachingWire` with regard to `this.cmch` instead of `"If-Modified-Since"`.

**Comment by amihaiemil** [comment]
@dmarkov I created PR #125 for this.

**Comment by dmarkov** [comment]
> @dmarkov I created PR #125 for this. 

@amihaiemil thank you!

**Comment by amihaiemil** [comment]
@dmarkov The pull request for this has been merged successfully.

**Comment by dmarkov** [comment]
> @dmarkov The pull request for this has been merged successfully.

@amihaiemil OK

**Comment by amihaiemil** [comment]
@dmarkov Is there something left that needs to be done here before closure? The PR was successfully merged and closed already.

**Comment by dmarkov** [comment]
@yegor256 Closed, thanks all

**Comment by dmarkov** [comment]
@amihaiemil Thank you, I have added **30 mins** to your account in payment/transaction "`AP-2NT531192B802444F`", time consumed: 169 hours and 54 mins

added +30 to your rating, now it is equal to [+30](http://www.netbout.com/b/36402?open=rating)
