### ISSUE TITLE
AbstractHeaderBasedCachingWire acts like a memory leak

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-http#124]
Currently, entries are never removed from the cache and there is no limit on the number of entries in the cache. Thus, it's effectively a memory leak.
A simplistic minimal way to address this would be:
- Add a constructor parameter for the maximum number of items in the `ConcurrentHashMap cache`
- Add a constructor parameter for an eviction algorithm, which will be invoked with the `cache` whenever the cache's size exceeds the maximum

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by andreoss** [comment]
@cvrebert Closing in favor of https://github.com/jcabi/jcabi-http/issues/179

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#124` is not assigned, can't get performer
