### ISSUE TITLE
Upgrade to grizzly web server 2.x

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-http#126]
Currently project uses 1.x line of grizzly web server, but there is already a 2.x line available with new features.
Notable feature is a way to tell grizzly to reserve a free port (by providing a `0` as a port number), this will solve #116 (see ~~https://java.net/jira/browse/GRIZZLY-1001~~ https://github.com/eclipse-ee4j/grizzly/issues/1001).

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by krzyk** [comment]
@yegor256 ping

**Comment by dmarkov** [comment]
@krzyk many thanks for the report, I topped your account for 15 mins, transaction 84050521

**Comment by 0pdd** [comment]
@krzyk the puzzle [#207](https://github.com/jcabi/jcabi-http/issues/207) is still not solved.

**Comment by 0pdd** [comment]
@krzyk the only puzzle [#207](https://github.com/jcabi/jcabi-http/issues/207) is solved here.

**Comment by andreoss** [comment]
@krzyk Upgraded to 2.4.4 in #205

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#126` is not assigned, can't get performer
