### ISSUE TITLE
Does jcabi-http Support Sending multipart/form-data?

### ISSUE THREAD

**Issue by jgl-jll** [jcabi/jcabi-http#131]
Does jcabi-http Support Sending multipart/form-data?

An example of the API I'm trying to call is:
https://strava.github.io/api/v3/uploads/

POST https://www.strava.com/api/v3/uploads

Thanks,
Jacob

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@jgl-jll nope, we don't have that

**Comment by piotrkot** [comment]
@jgl-jll According to https://github.com/jcabi/jcabi-http/pull/184, I think we do support it now. Sorry for the late answer.
