### ISSUE TITLE
Make JsonResponse.VerboseReader more flexible

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-http#132]
[JsonResponse.VerboseReader] (https://github.com/jcabi/jcabi-http/blob/5d7fb25dd1ba9e39aaf3ad5a129a37d1bc06cfc7/src/main/java/com/jcabi/http/response/JsonResponse.java) has 3 ``read`` methods to get the parsed json out of the response.

1) ``read()`` parses the response as a JsonStructure, which is hierarchicaly above ``JsonObject and Json Array``. Throws exception if there is any formatting error with the content. This is OK. 

2) ``readArray()`` currently tries to parse the content as ``JsonArray`` and **fails** if there is a formatting error in the content but ALSO if the given content is a ``JsonObject``. 

**Improvement:** If the content is a ``JsonObject`` this method should return a JsonArray with that object as only element. 

3) ``readObject()`` currently tries to parse the content as ``JsonObject`` and **fails** if there is a formatting error in the content but ALSO if the given content is a ``JsonArray``. 

**Improvement:** I the content is a ``JsonArray`` this method should return the first object in it or an empty ``JsonObject`` ( {} ) if the array is empty. 

These 2 improvements also refactor the code, like this: 

```
        @Override
        public JsonObject readObject() {
            JsonArray jarr = this.readArray();
            if(jarr.size() == 0) {
            	return Json.createObjectBuilder().build();
            }
            return jarr.getJsonObject(0);        	
        }
        @Override
        public JsonArray readArray() {
            return Json.createArrayBuilder().add(this.origin.read()).build();
        }
        
        @Override
        public JsonStructure read() {
            try {
                return this.origin.read();
            } catch (final JsonParsingException ex) {
                throw new JsonParsingException(
                    this.json, ex, ex.getLocation()
                );
            }
        }
```

Besides this, assertions in unit tests ``logsForInvalidJsonObject() and logsForInvalidJsonArray()`` need to be changed. Now exceptions reflect the most granular error, in the json structure formatting error.

**Comment by amihaiemil** [comment]
@dmarkov Can you see about this one pls?

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by amihaiemil** [comment]
@yegor256 can you have a look here pls? Thanks

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by amihaiemil** [comment]
@yegor256 Don't forget about this pls

**Comment by yegor256** [comment]
@amihaiemil I don't understand this:

> If the content is a JsonObject this method should return a JsonArray with that object as only element.

We should fail as often as possible (Fail Fast), but you're suggesting to make our code more tolerant to mistakes. That's just wrong. The same for your second suggestions. 

Read this: http://www.yegor256.com/2015/08/25/fail-fast.html
