### ISSUE TITLE
Tests are fragile

### ISSUE THREAD

**Issue by westonal** [jcabi/jcabi-http#135]
Had 1/2 failing/total build:
https://travis-ci.org/jcabi/jcabi-http/builds/130657365

Expected 2 passing builds:
https://travis-ci.org/jcabi/jcabi-http/builds/130705938

And there was no actual code changes between those commits.

Appears to fail randomly due to not being able to find a port:

> Tests in error: 
>   UserAgentWireTest.addsUserAgentHeader » Bind No free port within range: 43404=...

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by dmarkov** [comment]
@westonized many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `AP-36655606EG4877525`

**Comment by andreoss** [comment]
Continues as https://github.com/jcabi/jcabi-http/issues/200

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#135` is not assigned, can't get performer
