### ISSUE TITLE
MkGrizzlyAdapter, MkAnswer don't work properly with binary body

### ISSUE THREAD

**Issue by pstorch** [jcabi/jcabi-http#137]
`MkAnswer.Simple()` offers a Constructor with a `byte[]` body. But it's not possible to work with arbitrary binary content (e.g. images) here, because it is converted to `String` and `byte[]` back and forth with a default encoding of `UTF-8`.
`MkAnswer.body()` returns the body as a `String` and the `MkGrizzlyAdapter` again converts it to `byte[]`.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@dmarkov assign @westonized to this pls

**Comment by dmarkov** [comment]
> @dmarkov assign @westonized to this pls

@yegor256 done. @westonized you are assigned to this task. please proceed...

**Comment by westonized** [comment]
@dmarkov what happens here? OP's done the work I was working on.

**Comment by westonized** [comment]
@dmarkov it's OK, they have not done a PR, my mistake

**Comment by dmarkov** [comment]
> @dmarkov what happens here? OP's done the work I was working on.

@westonized yes, indeed. ignore them. it's your ticket, go ahead

**Comment by vrrs** [comment]
Any updates on this issue ? Its preventing to write tests with compressed files as bodies.

**Comment by dmarkov** [comment]
@rultor rultor closed it by mistake, @pstorch please take a look

**Comment by pstorch** [comment]
I'm fine with it

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#137` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#137](https://github.com/jcabi/jcabi-http/issues/137) was not in scope
