### ISSUE TITLE
Stopping JdkRequest

### ISSUE THREAD

**Issue by piotrkot** [jcabi/jcabi-http#154]
I have encountered sometimes problems when stopping `JdkRequest`. No matter if it's through a special `Wire` (like `OneMinuteWire`) or by `future.cancel(true)`. The issue can be related to jcabi-aspects.

**Comment by piotrkot** [comment]
It seems using `ApacheRequest` is more reliable.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@piotrkot what exactly is the problem? It doesn't stop?

**Comment by piotrkot** [comment]
@yegor256 Sorry that was a storm in a teacup. Anyway, I will share my findings.
I have integration tests with mocked server (using Takes framework). It was reproducible that Jdk requests were pending after the server was stopped.
That happened, firstly, because I had a bug in closing the server and sockets got stuck with CLOSE_WAIT status. Secondly, the killed Jdk requests had still open connection (TIME_WAIT). That made them log errors to the console but after a minute all TIME_WAIT sockets were hopefully gone.

**Comment by piotrkot** [comment]
I'm closing the issue.
