### ISSUE TITLE
JSON response with the Jackson Project 

### ISSUE THREAD

**Issue by chmodas** [jcabi/jcabi-http#157]
I often find myself including the JSONP (jsonp.java.net) dependencies while using Jackson everywhere else. A "JacksonResponse" would be ideal, in order to trim down the dependencies.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by chmodas** [comment]
I've created a pull request implementing this feature.

**Comment by yegor256** [comment]
@chmodas it's merged

**Comment by yegor256** [comment]
@rultor release, tag is `1.17`

**Comment by yegor256** [comment]
@rultor release, tag is `1.17`

**Comment by yegor256** [comment]
@rultor release, tag is `1.17`

**Comment by yegor256** [comment]
@rultor release, tag is `1.17`

**Comment by yegor256** [comment]
@rultor release, tag is `1.17`

**Comment by yegor256** [comment]
@chmodas try 1.17, it includes your changes. If it's done, please close the ticket

**Comment by 0crat** [comment]
Oops! Job `gh:jcabi/jcabi-http#157` was not in scope
