### ISSUE TITLE
BasicAuthWire URL encodes credentials (twice)

### ISSUE THREAD

**Issue by jakob-o** [jcabi/jcabi-http#159]
Hi,
unfortunately the BasicAuthWire is not usable with usernames / passwords that need to be URL encoded since 
```
final String info = URI.create(home).getUserInfo();
```
here https://github.com/jcabi/jcabi-http/blob/master/src/main/java/com/jcabi/http/wire/BasicAuthWire.java#L119
already requires username and password to be URL encoded and here
https://github.com/jcabi/jcabi-http/blob/master/src/main/java/com/jcabi/http/wire/BasicAuthWire.java#L131
they are getting encoded a second time which results in a bad Base64 encoded result.

A possible fix to this would be either to 
1. let the user (of the library) handle the URL encoding 
or
2. use a different method to retrieve the credentials from the URL and remove them from the resulting url (so that they don't require encoding in the first place)

The last one whilst making sure to keep backwards compatibilty (I assume) might however not be really transparent.

Regards

Jakob

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by jakob-o** [comment]
Addendum: If I am not mistaken, they actually must **not** be URL encoded at all to generate the Base64 string, this actually means the URL encode here
https://github.com/jcabi/jcabi-http/blob/master/src/main/java/com/jcabi/http/wire/BasicAuthWire.java#L131
should be a URL **de**code.

**Comment by yegor256** [comment]
@jakob-o make sense... Would be great if you can you create a unit test that proves that the code is broken and a fix, in a pull request. Can you do that or you want us to fix this issue?

**Comment by jakob-o** [comment]
@yegor256 Sure, but might take me a few days since I am busy. 

Regards

Jakob

**Comment by yegor256** [comment]
@jakob-o thanks, we'll wait!

**Comment by jakob-o** [comment]
@yegor256 Created #167

**Comment by yegor256** [comment]
@jakob-o thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `1.17.1`

**Comment by jakob-o** [comment]
@yegor256 Would you mind merging #165 too?

Regards

Jakob

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `1.17.1`

**Comment by yegor256** [comment]
@jakob-o version 1.17.1 is in Maven Central, try it out please

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#159` is not assigned, can't get performer
