### ISSUE TITLE
BaseRequest.java:470-476: Implement and unit test method...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-http#164]
The puzzle `87-bd2cb401` in [`src/main/java/com/jcabi/http/request/BaseRequest.java`](https://github.com/jcabi/jcabi-http/blob/master/src/main/java/com/jcabi/http/request/BaseRequest.java) (lines 470-476) has to be resolved: Implement and unit test method formParam(String, Object) Details

here

(second answer).

e.g. While FormEncodedBody.formParam adds the param to a body with enctype application/x-www-form-urlencoded, method MultipartFormBody.formParam should add it to a body with enctype multipart/form-data.

The puzzle was created by amihaiemil on 10-Aug-16. 

Estimate: 60 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by amihaiemil** [comment]
@yegor256 Can I do this? I need it in multipart form functionality completed for another project.

**Comment by yegor256** [comment]
@amihaiemil you can, but we're not paying for open source contribution anymore

**Comment by amihaiemil** [comment]
@yegor256 sure :)

**Comment by amihaiemil** [comment]
I looked over this, but it's harder then expected -- I think there will need to be little changes in the interfaces too. Until I manage to fix it, users could upload files by constructing their own request body, "manually". It's all explained pretty clrearly in this RFC: https://tools.ietf.org/html/rfc7578

**Comment by 0pdd** [comment]
The puzzle `87-bd2cb401` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#164` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
