### ISSUE TITLE
Scope of BaseRequest class

### ISSUE THREAD

**Issue by RishikeshDarandale** [jcabi/jcabi-http#170]
https://github.com/jcabi/jcabi-http/blob/3fb96cb2d5fca37f729b932e3d71f8a79c94c05c/src/main/java/com/jcabi/http/request/BaseRequest.java#L82

is there any reason to keep the scope of the class as limited? 
I want to provide an another concrete implementation of `Request` interface with using the `BaseRequest` functionality.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `1.17.2`

**Comment by yegor256** [comment]
@RishikeshDarandale check version 1.17.2.

**Comment by RishikeshDarandale** [comment]
Thanks @yegor256 for a quick turnaround! Appreciate that!

**Comment by RishikeshDarandale** [comment]
@yegor256 , you need to define the constructors as `public` as well.

**Comment by yegor256** [comment]
@rultor release, tag is `1.17.3`

**Comment by yegor256** [comment]
@rultor release, tag is `1.17.3`

**Comment by yegor256** [comment]
@rultor release, tag is `1.17.3`

**Comment by andreoss** [comment]
@RishikeshDarandale Fixed. `BaseRequest` is public with public ctors in [1.17.3](https://github.com/jcabi/jcabi-http/releases/tag/1.17.3)

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#170` is not assigned, can't get performer
