### ISSUE TITLE
upgrade to jcabi 1.24

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-http#171]
Let's upgrade jcabi parent pom to version 1.24 and fix all Checkstyle and PMD issues.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#171` is in scope.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+6385](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/jcabi/jcabi-http/issues/171#issuecomment-383534235))

@yegor256 GitHub issue is still open, won't close

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job [#171](https://github.com/jcabi/jcabi-http/issues/171) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#171](https://github.com/jcabi/jcabi-http/issues/171); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#171](https://github.com/jcabi/jcabi-http/issues/171); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#171](https://github.com/jcabi/jcabi-http/issues/171); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#171](https://github.com/jcabi/jcabi-http/issues/171); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#171](https://github.com/jcabi/jcabi-http/issues/171); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#171](https://github.com/jcabi/jcabi-http/issues/171); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#171](https://github.com/jcabi/jcabi-http/issues/171); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#171](https://github.com/jcabi/jcabi-http/issues/171); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by andreoss** [comment]
As were discussed elsewhere, the version of parent should be `1.25.1`

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#194](https://github.com/jcabi/jcabi-http/issues/194), [#195](https://github.com/jcabi/jcabi-http/issues/195) are still not solved.

**Comment by yegor256** [comment]
@rultor release, tag is `1.17.3`

**Comment by yegor256** [comment]
@andreoss many thanks!

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#171` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#194](https://github.com/jcabi/jcabi-http/issues/194), [#199](https://github.com/jcabi/jcabi-http/issues/199) are still not solved; solved: [#195](https://github.com/jcabi/jcabi-http/issues/195).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#194](https://github.com/jcabi/jcabi-http/issues/194), [#206](https://github.com/jcabi/jcabi-http/issues/206) are still not solved; solved: [#195](https://github.com/jcabi/jcabi-http/issues/195), [#199](https://github.com/jcabi/jcabi-http/issues/199).

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#194](https://github.com/jcabi/jcabi-http/issues/194), [#210](https://github.com/jcabi/jcabi-http/issues/210) are still not solved; solved: [#195](https://github.com/jcabi/jcabi-http/issues/195), [#199](https://github.com/jcabi/jcabi-http/issues/199), [#206](https://github.com/jcabi/jcabi-http/issues/206).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#194](https://github.com/jcabi/jcabi-http/issues/194) is still not solved; solved: [#195](https://github.com/jcabi/jcabi-http/issues/195), [#199](https://github.com/jcabi/jcabi-http/issues/199), [#206](https://github.com/jcabi/jcabi-http/issues/206), [#210](https://github.com/jcabi/jcabi-http/issues/210).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#331](https://github.com/jcabi/jcabi-http/issues/331) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#unknown]() is still not solved; solved: [#331](https://github.com/jcabi/jcabi-http/issues/331).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#635](https://github.com/jcabi/jcabi-http/issues/635) is still not solved; solved: [#194](https://github.com/jcabi/jcabi-http/issues/194), [#195](https://github.com/jcabi/jcabi-http/issues/195), [#199](https://github.com/jcabi/jcabi-http/issues/199), [#206](https://github.com/jcabi/jcabi-http/issues/206), [#210](https://github.com/jcabi/jcabi-http/issues/210).
