### ISSUE TITLE
class file for org.hamcrest.Matcher not found

### ISSUE THREAD

**Issue by ashtonhogan** [jcabi/jcabi-http#172]
I added this dependency to my project:

```
        <dependency>
            <groupId>com.jcabi</groupId>
            <artifactId>jcabi-http</artifactId>
            <version>1.17.2</version>
        </dependency>
```

Then I make a request and assert the status from the response:

` restResponse.assertStatus(409);`

When I try to clean and build it, the above line gives this error:

> class file for org.hamcrest.Matcher not found

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan see http://http.jcabi.com/optional-dependencies.html (closer to the bottom).

**Comment by ashtonhogan** [comment]
@yegor256 why not include them in yours?

**Comment by yegor256** [comment]
@ashtonhogan because not every project needs them. Sometimes you don't need to use any assertions, but just want to do `new JdkRequest("http://goog.com").fetch().body()`. In this case, you don't need any dependencies at all.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
