### ISSUE TITLE
Maven javadoc plugin complains

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-http#173]
It [started](https://github.com/jcabi/jcabi-http/issues/170#issuecomment-356031132) complaining about certain annotations found in the javadocs. We have to fix this in order to release the new version.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#173` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#173](https://github.com/jcabi/jcabi-http/issues/173) was not in scope
