### ISSUE TITLE
The "cookie" method does not work properly

### ISSUE THREAD

**Issue by driver733** [jcabi/jcabi-http#176]
I am trying to use the `cookie` method to retrieve a cookie. However, it seems that it is only able to retrieve the first cookie.
```
for (String s : auth.headers().get("Set-Cookie")) {
            System.out.println(s);
        }
// user_lang=ru; expires=Tue, 13-Jun-2023 13:51:17 GMT; Max-Age=157766400; path=/; domain=.amocrm.ru
// BITRIX_SM_SALE_UID=0; expires=Sat, 08-Jun-2019 13:51:17 GMT; Max-Age=31104000; path=/; domain=.amocrm.ru; secure; httponly
// BITRIX_SM_LOGIN=login; expires=Thu, 18-May-2023 13:51:17 GMT; Max-Age=155520000; path=/; domain=.amocrm.ru; secure; httponly
// session_id=uasdfjk1234sadfjk32; path=/; domain=.amocrm.ru; secure; HttpOnly
```
```
System.out.println(auth.cookie("user_lang").getValue()); 
// ru
System.out.println(auth.cookie("BITRIX_SM_SALE_UID").getValue()) 
// Exception: Not found
System.out.println(auth.cookie("BITRIX_SM_LOGIN").getValue()) 
// Exception: Not found
System.out.println(auth.cookie("session_id").getValue())
// Exception: Not found
```

The code in the cookie method is equivalent to the following
for (HttpCookie cookie : HttpCookie.parse(auth.headers().get(HttpHeaders.SET_COOKIE).toString())) {
            System.out.println(cookie);
 }
// [user_lang=ru

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@driver733[/z](https://www.0crat.com/u/driver733) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by driver733** [comment]
The `cookie` method uses the `HttpCookie.parse` method on the whole `Set-Cookie` header. Instead, it must call the`HttpCookie.parse` method on each cookie.

**Comment by andreoss** [comment]
@driver733 Fixed.
