### ISSUE TITLE
Handle redirects with Authorization header

### ISSUE THREAD

**Issue by marcguilera** [jcabi/jcabi-http#181]
I am trying to download a file from a GitHub release using the [api](https://developer.github.com/v3/repos/releases/#response-8) but it seems that upon redirection the `Authorization` header gets messed with based on [this](https://stackoverflow.com/questions/31514336/only-one-auth-mechanism-allowed-only-the-x-amz-algorithm-query-parameter/46992561) response. 

This is what I'm doing:

```
/**
 * Downloads an asset from the release.
 */
fun ReleaseAsset.downloadStream(): InputStream {
    // Hack because the lib is missing nice download support. =(
    // see https://developer.github.com/v3/repos/releases/#response-8
    val coords = release().repo().coordinates()
    val id = ReleaseAsset
            .Smart(this)
            .json()
            .getInt("id")

    return release()
            .repo()
            .github()
            .entry()
            .method(Request.GET)
            .reset(HttpHeaders.ACCEPT)
            .header(HttpHeaders.ACCEPT, MediaType.APPLICATION_OCTET_STREAM_VALUE)
            .uri()
                .path("/repos")
                .path("/${coords.user()}")
                .path("/${coords.repo()}")
                .path("/releases")
                .path("/assets")
                .path("/$id")
                .back()
            .fetch()
            .binary()
            .apply { println(String(this)) }
            .inputStream()
}

```

And the error that gets printed:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>token xxxxx</ArgumentValue><RequestId>1F6EF1EE2CE6010D</RequestId><HostId>xxxxx</HostId></Error>
```

Please note that I'm using the jcabi GitHub lib. 

-----

PS: Should the lib support downloads itself?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@marcguilera[/z](https://www.0crat.com/u/marcguilera) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@marcguilera that's a good question. I don't see any errors in your code. Can you try to check the logs to see exactly what HTTP request is being sent?

**Comment by marcguilera** [comment]
I am away from my computer for a couple days so I can't share the code
right now but I was able to fix it by adding a wire which detects if both
auth methods (header and path) are present and removes the header.

**Comment by andreoss** [comment]
@marcguilera I believe you should file it to [jcabi-github](https://github.com/jcabi/jcabi-github)
I see no indication that the problem originates from `jcabi-http`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#181` is not assigned, can't get performer
