### ISSUE TITLE
Allow for "Wire" instances to be directly used in "Request"

### ISSUE THREAD

**Issue by pinaf** [jcabi/jcabi-http#182]
Currently using a wire means calling
```java
<T extends Wire> Request through(Class<T> var1, Object... var2);
```
which leaves the instantiation of the `Wire` object to the request itself, using reflection.

Let's instead add a method
```java
Request through(Wire wire);
```
to the `Request` interface so that `Wire` instances which we control can be used directly.
Besides being a better OOP design, it'll allow for better unit testing which verifies whether a given `Wire` instance was used/called.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@pinaf[/z](https://www.0crat.com/u/pinaf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@pinaf sure, let's do it, but in addition to the existing reflection-based functionality. Want to submit a PR?

**Comment by pinaf** [comment]
@yegor256 please see #183

**Comment by yegor256** [comment]
@pinaf thanks, the version `0.18.0` is released

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#182` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by yegor256** [comment]
@rultor release, tag is `1.18.0`

**Comment by yegor256** [comment]
@pinaf can't release. We have to upgrade to jcabi 1.24 and try again: https://github.com/jcabi/jcabi-http/issues/171
