### ISSUE TITLE
Master builds fail on AppVeyor and Travis

### ISSUE THREAD

**Issue by piotrkot** [jcabi/jcabi-http#185]
Automatic builds in CI: AppVeyor and Travis fail.
I believe this is a critical issue as no-one can work with the project if the build on the master branch fails.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@piotrkot[/z](https://www.0crat.com/u/piotrkot) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@piotrkot Travis is clean now

**Comment by yegor256** [comment]
@piotrkot this is an absolute mystery for me: https://ci.appveyor.com/project/yegor256/jcabi-http/branch/master Can you help?

**Comment by piotrkot** [comment]
@yegor256 Oh, come on. You're the master here :)
I spent some time investigating and I gave up. I can spend some more.

**Comment by andreoss** [comment]
@piotrkot  Closing this in favor of #224

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#185` is not assigned, can't get performer
