### ISSUE TITLE
pom.xml:151-157: Migrate all simple tests to Junit 5. For...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-http#195]
The puzzle `171-01da2b80` from #171 has to be resolved: 

https://github.com/jcabi/jcabi-http/blob/b76b7f4fd946a721fe4256d3ae06d5f2056b5c8b/pom.xml#L151-L157

The puzzle was created by andreoss on 25-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#195](https://github.com/jcabi/jcabi-http/issues/195); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#195](https://github.com/jcabi/jcabi-http/issues/195); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0pdd** [comment]
The puzzle `171-01da2b80` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#199](https://github.com/jcabi/jcabi-http/issues/199) is still not solved.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#195` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd the puzzle [#206](https://github.com/jcabi/jcabi-http/issues/206) is still not solved; solved: [#199](https://github.com/jcabi/jcabi-http/issues/199).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#210](https://github.com/jcabi/jcabi-http/issues/210) is still not solved; solved: [#199](https://github.com/jcabi/jcabi-http/issues/199), [#206](https://github.com/jcabi/jcabi-http/issues/206).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#199](https://github.com/jcabi/jcabi-http/issues/199), [#206](https://github.com/jcabi/jcabi-http/issues/206), [#210](https://github.com/jcabi/jcabi-http/issues/210).
