### ISSUE TITLE
pom.xml:151-155: Migrate the rest of tests to Junit 5....

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-http#199]
The puzzle `195-eea7018e` from #195 has to be resolved: 

https://github.com/jcabi/jcabi-http/blob/866d7608f6fe6d81c27320f867b8921efb40d7ff/pom.xml#L151-L155

The puzzle was created by andreoss on 07-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#199](https://github.com/jcabi/jcabi-http/issues/199); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0pdd** [comment]
The puzzle `195-eea7018e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#206](https://github.com/jcabi/jcabi-http/issues/206) is still not solved.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#199` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd the puzzle [#210](https://github.com/jcabi/jcabi-http/issues/210) is still not solved; solved: [#206](https://github.com/jcabi/jcabi-http/issues/206).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#206](https://github.com/jcabi/jcabi-http/issues/206), [#210](https://github.com/jcabi/jcabi-http/issues/210).
