### ISSUE TITLE
Test fails on Travis-CI

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi-http#200]
`TrustedWireITCase` is failing on Travis [1] while passing locally.
It tries to access https://api.travis-ci.org/test and expects 404, but the server answers with 403.
The reason for testing `TrustedWire` with this particular link is unclear (there is no issues with its SSL certificate).
Consider using https://badssl.com/ for testing with self-signed and expired certificates.

[1]: https://travis-ci.org/github/jcabi/jcabi-http/builds/705946698

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#200](https://github.com/jcabi/jcabi-http/issues/200); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0pdd** [comment]
@andreoss the puzzle [#202](https://github.com/jcabi/jcabi-http/issues/202) is still not solved.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#200` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@andreoss the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@andreoss the only puzzle [#202](https://github.com/jcabi/jcabi-http/issues/202) is solved here.
