### ISSUE TITLE
MkGrizzlyContainer.java:173-176: Grizzly Server has...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-http#207]
The puzzle `126-c5eb9db3` from #126 has to be resolved: 

https://github.com/jcabi/jcabi-http/blob/b00f0aa072e64ad270214d8a80222fc8c5e9781e/src/main/java/com/jcabi/http/mock/MkGrizzlyContainer.java#L173-L176

The puzzle was created by @rultor on 09-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#207](https://github.com/jcabi/jcabi-http/issues/207) doesn't exist, can't set role

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#207](https://github.com/jcabi/jcabi-http/issues/207); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0pdd** [comment]
The puzzle `126-c5eb9db3` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#207](https://github.com/jcabi/jcabi-http/issues/207); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
