### ISSUE TITLE
JsonResponseTest.java:43-45: Use assertThrows instead of...

### ISSUE THREAD

**Issue by 0pdd** [jcabi/jcabi-http#210]
The puzzle `206-f3551294` from #206 has to be resolved: 

https://github.com/jcabi/jcabi-http/blob/517d46212b5fd876c880b89a231d53e6528def01/src/test/java/com/jcabi/http/response/JsonResponseTest.java#L43-L45

The puzzle was created by andreoss on 10-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `206-f3551294` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#210` is not assigned, can't get performer
