### ISSUE TITLE
Move to Github Actions 

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi-http#224]
Alike `takes` and `cactoos`, use Github actions in order to build on various platforms.
This would make possible to deprecate AppVeyor and Travis in the future (see #185)

**Comment by andreoss** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/jcabi/jcabi-http/issues/224#issuecomment-724601087))

@andreoss You @andreoss[/z](https://www.0crat.com/u/andreoss) need to have one of these roles in order to do "Add job to WBS": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by andreoss** [comment]
@yegor256 Since GH Actions are now enabled, can you disable travis and appveyor?
Appveyor has been broken for sometime, and travis is now redundant and slower than GHA

**Comment by yegor256** [comment]
@andreoss it's done
