### ISSUE TITLE
upgrade to 1.27.0

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-http#227]
Let's upgrade our `pom.xml` to the latest parent: 1.27.0

**Comment by andreoss** [comment]
@yegor256 I think we should setup @dependabot for jcabi organization

**Comment by andreoss** [comment]
@yegor256 Done.

**Comment by yegor256** [comment]
@andreoss let's release?

**Comment by yegor256** [comment]
@andreoss I added dependabot to all repos

**Comment by andreoss** [comment]
@rultor release, tag `1.17.4`

**Comment by andreoss** [comment]
@rultor release, tag=`1.17.4`
