### ISSUE TITLE
Grizzly container is unable to handle DELETE with a payload

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi-http#238]
The current container configuration is set up to ignore DELETE requests with a payload, 400 Bad Request is returned instead

Can be reproduced with this test:
```
    @Test
    void handlesDeleteWithBody() throws Exception {
        try (final MkContainer container = new MkGrizzlyContainer()
            .next(
                new MkAnswer.Simple(
                    HttpURLConnection.HTTP_OK,
                    Json.createObjectBuilder().toString()
                )
            ).start()) {
            new ApacheRequest(container.home())
                .method(Request.DELETE)
                .body().set("{}").back()
                .fetch()
                .as(RestResponse.class)
                .assertStatus(HttpURLConnection.HTTP_OK)
                .as(JsonResponse.class)
                .json();
            MatcherAssert.assertThat(
                container.take().method(),
                Matchers.is("DELETE")
            );
        }
    }

```

See: https://stackoverflow.com/questions/49976638/allow-delete-requests-with-message-body-using-grizzly-servlet-container
See: https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

**Comment by andreoss** [comment]
@0crat assign @andreoss

**Comment by andreoss** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat assign @andreoss  ([here](https://github.com/jcabi/jcabi-http/issues/238#issuecomment-762082524))

@andreoss You @andreoss[/z](https://www.0crat.com/u/andreoss) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by andreoss** [comment]
@rultor release, tag=`1.17.5`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/jcabi/jcabi-http/issues/238#issuecomment-762083252))

@andreoss You @andreoss[/z](https://www.0crat.com/u/andreoss) need to have one of these roles in order to do "Add job to WBS": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by andreoss** [comment]
@rultor release, tag=`1.17.5`

**Comment by andreoss** [comment]
@rultor release, tag=`1.17.5`

**Comment by andreoss** [comment]
@rultor release, tag=`1.17.5`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#238` is not assigned, can't get performer
