### ISSUE TITLE
AutoRedirectingWire does not work if location is relative

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi-http#252]
Location is incorrectly resolved on this line:
https://github.com/jcabi/jcabi-http/blob/771cf34cb1fbe4d68206c1b6e5ab89808ad1d810/src/main/java/com/jcabi/http/wire/AutoRedirectingWire.java#L126-L129

**Comment by AyushWalekar** [comment]
Hi @andreoss , I am new to the open source, starting contribution with this. Please let me know if I can pick this up.
Thanks!

**Comment by andreoss** [comment]
@AyushWalekar Sure you can

**Comment by andreoss** [comment]
@AyushWalekar Any success?

**Comment by AyushWalekar** [comment]
@andreoss apologies for the delay, I missed notification earlier.
I'll start looking it right away.

**Comment by AyushWalekar** [comment]
@andreoss I looked into the issue but was unable to reproduce i.e. URL was resolved as expected, even though location.get(0) returned relative path.

This is how is tested:
Ran the 

- test case 'returnsValidResponseAfterRetry' in [AutoRedirectingWireTest.java](https://github.com/jcabi/jcabi-http/blob/66319a4ba32252b72a5f20a64c70cc8a80d04a7d/src/test/java/com/jcabi/http/wire/AutoRedirectingWireTest.java#L88)

Can you please help reproduce the issue or let me know if I am missing anything. Thanks!

![image](https://user-images.githubusercontent.com/18314823/124113918-99c2fe80-da89-11eb-8d5b-58c03af2d4c4.png)

**Comment by andreoss** [comment]
@AyushWalekar 
I'm pretty sure that there is a bug.
This line in particular looks very wrong, it just disregards the header completely 
https://github.com/jcabi/jcabi-http/blob/771cf34cb1fbe4d68206c1b6e5ab89808ad1d810/src/main/java/com/jcabi/http/wire/AutoRedirectingWire.java#L128

Here is the test for absolute location:
https://github.com/jcabi/jcabi-http/blob/e37b67bfca2731f46dc34dff1a138039cbc4eceb/src/test/java/com/jcabi/http/RequestITCaseTemplate.java#L148

You have to add one for relative location (https://httpbin.org/#/Redirects/get_relative_redirect__n_), which will fail until you fix this bug.

The integration test suite uses `HttpBin` (https://httpbin.org/) in Docker, so make sure you have Docker setup on your machine.

**Comment by AyushWalekar** [comment]
@andreoss Thank you so much, I was able to reproduce the issue with your help.
Created PR #271

**Comment by andreoss** [comment]
@AyushWalekar Thanks
