### ISSUE TITLE
Update to Jakarta EE 9 spec

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi-http#265]
- Migrate from `javax.ws` to `jakarta.ws` API
- Upgrade jersey & glassfish dependencies to 3.0

**Comment by markBowman** [comment]
I would like to up-vote this issue. 
Currently, any client with a dependency on jcabi-http attempting to compile under Java 17 is confounded by "NoClassDefFound javax/ws/rs/core/UriBuilder" or similar errors.
I am happy to act as a beta tester.

**Comment by andreoss** [comment]
Done in #432

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#265` is not assigned, can't get performer
