### ISSUE TITLE
new skin 1.7.1

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-http#278]
New Maven skin

**Comment by yegor256** [comment]
@andreoss let's release?

**Comment by andreoss** [comment]
@rultor release, tag=`1.17.5`

**Comment by andreoss** [comment]
@yegor256 Should it resolve #203?

**Comment by andreoss** [comment]
@rultor release, tag=`1.18.0`

**Comment by andreoss** [comment]
@rultor release, tag=`1.18.0`

**Comment by andreoss** [comment]
@yegor256 CoverAll issues is fixed, but now the artifacts from the previous attempt are staged. Do you have rights to remove them?

**Comment by yegor256** [comment]
@andreoss nobody can remove them. just release the next version (1.18.1)

**Comment by andreoss** [comment]
@rultor release, tag=`1.18.1`

**Comment by yegor256** [comment]
@andreoss now it's all cool, thanks!
