### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi-http#432]
- Move to Jakarta API https://github.com/jcabi/jcabi-http/pull/417
- Various dependency updates 
  - https://github.com/jcabi/jcabi-http/pull/412 
  - https://github.com/jcabi/jcabi-http/pull/422

**Comment by andreoss** [comment]
@rultor release, tag is `2.0.0`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#432` is not assigned, can't get performer
