### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-http#59]
Copyright sections still feature 2014 as a year.

**Comment by yegor256** [comment]
@maurezen fixed in 1fdc10b, thanks!

**Comment by maurezen** [comment]
@yegor256 why the invalid label? this was a valid bug which you took time to fix.

**Comment by yegor256** [comment]
@maurezen it's too small/cosmetic, see http://www.teamed.io/policy.html#13

**Comment by maurezen** [comment]
@yegor256 so "invalid" is "not paid", right? But it is also used when the issue in question is not a bug. Shouldn't there be a difference?

**Comment by yegor256** [comment]
@maurezen yeah, ideally there should be, but Github doesn't have a specific tag for "not-a-bug". that's why "invalid" is good enough
