### ISSUE TITLE
Restrict type parameter in Response.as(Class<T> type) method to accept implementations of Response only

### ISSUE THREAD

**Issue by invisible-arrow** [jcabi/jcabi-http#60]
Currently Response.as(Class&lt;T&gt; type) accepts any type without bounds on T.
It should be restricted to implementations of Response interface.
Something like: &lt;T extends Response&gt; T as(Class&lt;T&gt; type)
This will also help as a good self documentation of the method.

**Comment by yegor256** [comment]
@invisible-arrow thanks for reporting, we'll fix it!

**Comment by dmarkov** [comment]
I'll ask someone to take care of this task soon

**Comment by dmarkov** [comment]
@romankisilenko this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by RomanKisilenko** [comment]
@invisible-arrow PR was reviewed and closed, please close this issue.

**Comment by invisible-arrow** [comment]
@RomanKisilenko, @yegor256 Thanks. Closing the issue.

**Comment by dmarkov** [comment]
@romankisilenko Thanks for your contribution, **30 mins** was added to your account, payment ID is `50616612`

+30 to your rating, your total score is +390

**Comment by jtsiros** [comment]
I think this breaks the fact that you can't use .as(HttpResponse.class).assertStatus(...). Since T is now bound to type T extending Response, things like HttpResponse.class from org.apache.http.HttpResponse don't seem to work. Is there an alternative to HttpResponse that was implemented?

**Comment by yegor256** [comment]
@jtsiros could you please report a new issue, explaining there what exactly doesn't work (with code examples please). thanks!
