### ISSUE TITLE
http://http.jcabi.com documentation contains wrong snapshot version

### ISSUE THREAD

**Issue by RomanKisilenko** [jcabi/jcabi-http#62]
Version 1.0-SNAPSHOT is mentioned in docs 2.0-SNAPSHOT.

**Comment by dmarkov** [comment]
we'll find someone to do this task, soon

**Comment by dmarkov** [comment]
@maurezen it's your task, go ahead

**Comment by dmarkov** [comment]
@romankisilenko thank you for the ticket reported, I topped your account for 15 mins, transaction `50342743`

**Comment by maurezen** [comment]
@dmarkov created a pull request here #65

**Comment by maurezen** [comment]
@RomanKisilenko pull request #65 merged, please close the issue.

**Comment by maurezen** [comment]
@RomanKisilenko please close the issue.

**Comment by maurezen** [comment]
@dmarkov this issue is closed.

**Comment by dmarkov** [comment]
@maurezen Thank you, I've added **30 mins** to your account in payment/transaction "`50614412`"; +30 added to your rating, current score is: [+855](http://www.netbout.com/b/35102?open=rating)
