### ISSUE TITLE
mvm clean verify fails

### ISSUE THREAD

**Issue by RomanKisilenko** [jcabi/jcabi-http#63]
During test compilation, maven build fails with errors like
```
[ERROR] /Users/roman/Desktop/project/teamio/jcabi-http/src/test/java/com/jcabi/http/wire/CookieOptimizingWireTest.java:[84,25] <U>everyItem(org.hamcrest.Matcher<U>) in org.hamcrest.Matchers cannot be applied to <java.lang.String>(org.hamcrest.Matcher<java.lang.Object>)
```

**Comment by yegor256** [comment]
@RomanKisilenko hm.. Travis build is clean. how can I reproduce this issue? how do you run the build? what are your Maven/Java version?

**Comment by RomanKisilenko** [comment]
Java 6 was used for compilation. Java 8 compiles fine. So this one can be closed I think.
