### ISSUE TITLE
Missing Lombok dependency

### ISSUE THREAD

**Issue by davidsowerby** [jcabi/jcabi-http#64]
Thanks for this very useful library - I was getting version conflicts with anything that uses ApacheHttp, and this gave me a very quick solution.

There does seem to be a dependency missing from your "optional dependencies" page, for the the Lombok annotations.

In Gradle speak:    

> compile 'org.projectlombok:lombok:1.14.8'

I'm currently using:

>   compile 'com.jcabi:jcabi-http:1.10.1'
>     compile 'javax.json:javax.json-api:1.0'
>     compile 'org.glassfish:javax.json:1.0.4'

**Comment by yegor256** [comment]
@davidsowerby thanks for using jcabi :) this may be a bug in our documentation or in our pom.xml. I'll investigate. thanks for reporting!

**Comment by andreoss** [comment]
@davidsowerby lombok is a compile-time dependency now, and has been for at least several releases.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#64` is not assigned, can't get performer
