### ISSUE TITLE
Add RestResponse.assertBinary() method

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-http#73]
At the moment, we have a method `RestResponse.assertBody(Matcher<String>)`, which checks if the response body String corresponds to the given matcher.

Let's add an equivalent `assertBinary()` method for checking binary content. After all, we have methods to obtain the response in either format (`Response.body()` and `Response.binary()` respectively); it would be great if we were able to have convenience methods for verifying the body content in binary as well.

**Comment by dmarkov** [comment]
we will find someone to do this task, soon

**Comment by dmarkov** [comment]
@carlosmiranda thank you for the ticket reported, I topped your account for 15 mins, transaction `54559173`

**Comment by antonini** [comment]
@dmarkov @yegor256 Please assign this task to me.

**Comment by yegor256** [comment]
@dmarkov assign @antonini to this task pls

**Comment by antonini** [comment]
Implemented but waiting the issue be assigned.

**Comment by yegor256** [comment]
@dmarkov assign @antonini to this task pls

**Comment by dmarkov** [comment]
> @dmarkov assign @antonini to this task pls

@yegor256 OK @antonini please start, the task is yours

**Comment by antonini** [comment]
@carlosmiranda Source code was merged.

**Comment by carlosmiranda** [comment]
@antonini Thanks! Closing...

**Comment by dmarkov** [comment]
@antonini Thanks for your contribution, **38 mins** was added to your account, payment ID is `AP-3R530419KW772193W`, 71 hours and 34 mins spent total; m=4294, that's why a bonus here for fast delivery; added +38 to your rating, now it is equal to [+38](http://www.netbout.com/b/35346?open=rating)
