### ISSUE TITLE
Improvement: Path can supply template with params

### ISSUE THREAD

**Issue by longtimeago** [jcabi/jcabi-http#75]
It would be really cool to have ```RequestURI.path(String format, Object ... params)```
to be able to set path params like this:
```java
    new ApacheRequest("https://www.google.com")
      .uri().path("/users/{}/{}", "12345", "6789").back()
      .method(Request.GET)
      .header(HttpHeaders.ACCEPT, MediaType.TEXT_HTML)
      .fetch()
      .as(HttpResponse.class)
      .assertStatus(HttpURLConnection.HTTP_OK)
      .body();
  }
```
which will result in following request:
``` /users/12345/6789 ```

**Comment by yegor256** [comment]
@longtimeago what's wrong with `.path("users").path("12345").path("6789")`?

**Comment by longtimeago** [comment]
@yegor256 too verbose :)

**Comment by yegor256** [comment]
@longtimeago nah :) we won't fix this, but thanks for the suggestion

**Comment by longtimeago** [comment]
@yegor256 Oook, let me explain :)
Consider, following path (don't ask to change the path, I can't):
```
/users/{userId}/docs/{docId}/lines/{lineId}
```
Suppose, we need to call this resource in from many many tests with different parameters.
Proposed improvement would be very helpful.
With current jcabi-http api it would be too verbose. Or ... am I missed something?

**Comment by longtimeago** [comment]
@yegor256 still no?

**Comment by yegor256** [comment]
@longtimeago design-wise, I don't think it's a good idea to use any `TEMPLATE` constants. I would rather create an instance of `Request` and re-use it:

```
Request req = new JdkRequest("..").uri().path("/users").("222").path("/docs").back();
```

And later in tests:

```
req.uri().path("something-extra").back().fetch();
```

**Comment by longtimeago** [comment]
@yegor256 you've ignored my second example. It's not so straightforward
```
/users/{userId}/docs/{docId}/lines/{lineId}
```
With current jcabi-http I have to do:
```java
Request req = new JdkRequest("..").uri().path("/users").("222").path("/docs").path("111").path("/lines").path("444").back();
```
With template:
```java
Request req = new JdkRequest("..").uri().path(template, "222", "111", "444").back();
```
What do you think?

**Comment by longtimeago** [comment]
P.S. We just trying to choose between jcabi-http and rest-assured (https://github.com/jayway/rest-assured) . 
rest-assured is less verbose while still doing the same (with path templates by the way).

**Comment by yegor256** [comment]
@longtimeago I think verbosity in this case is only making code cleaner. This templating (from JAX-RS), in my opinion, is a bad idea.

**Comment by longtimeago** [comment]
@yegor256 could you please elaborate why templating is bad idea? Is it bad for lib or for the lib client?

**Comment by yegor256** [comment]
@longtimeago I think that templating in this particular case (and in many others) is doing two jobs at the same time. The URI builder is 1) composing URI from components, and 2) formatting components. That's one job too many. It's better to let components format themselves and URI builder will just put them together, separating with slash.

**Comment by longtimeago** [comment]
@yegor256 so, you just confirm that it's bad for lib :)
Thanks!
