### ISSUE TITLE
get rid of JAX-RS dependency

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-http#76]
Let's get rid of JAX-RS dependency in runtime/compile scope.

**Comment by dmarkov** [comment]
I will find a developer for the task soon...

**Comment by dmarkov** [comment]
@yegor256 thanks for this report, I added 15 mins to your account, in transaction `000-388ae7c7`

**Comment by yegor256** [comment]
@rultor hello

**Comment by yegor256** [comment]
@rultor status

**Comment by andreoss** [comment]
@yegor256 What is the reason for removing JAX-RS dependencies? May be we should upgrade to JAX-RS 2.0 instead?

**Comment by andreoss** [comment]
@yegor256 Closing in favor of https://github.com/jcabi/jcabi-http/issues/211

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-http#76` is not assigned, can't get performer
