### ISSUE TITLE
JdkRequest - Capitalize First Letter in response header names

### ISSUE THREAD

**Issue by bugs84** [jcabi/jcabi-http#81]
JdkRequest - Capitalize First Letter in response header names.
This is caused by ImmutableHeader class, which capitalize first letters in header name.

I love jcabi-http :) , but
My tests are failing when i get "different" headers

Here is small unit test:

    import com.jcabi.http.ImmutableHeader;
    import org.junit.Test;
    
    import static org.hamcrest.CoreMatchers.is;
    import static org.junit.Assert.assertThat;
    
    public class CapitalizingHeadersTest {
    
        @Test
        public void caseInHeaderIsNotChanged() {
            ImmutableHeader immutableHeader = new ImmutableHeader("headerName", "headerValue");
    
            assertThat(immutableHeader.getKey(), is("headerName"));
        }
    }

which fails in this way:

    java.lang.AssertionError: 
    Expected: is "headerName"
         but: was "HeaderName"

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@bugs84 sorry for the delay in replying. this is by design. we capitalize all headers, as they should be in HTTP. why can't you just correct your tests?

**Comment by bugs84** [comment]
I know, that headers should start with capital letter. But I am writing a proxy application. And my proxy is resending headers as they are. Some (third-party) applications use bad headers (without capital letter). And these applications doesn't work, when gets "HeaderName" isnstead of "headerName".
I think, that jcabi-http is HttpClient and i should be able send what ever header I want and jcabi-http should not change header.
I was very surprised, that jcabi-http automatically "correct" my headeras, that I want send. I don't know any good reason why it should do that.
This is just my suggestion. It's up to you how jcabi-http will work :)

**Comment by yegor256** [comment]
@bugs84 well, we're trying to be HTTP compliant, that's why correcting you when you're making "mistakes" :) it's by design, we can't change that

**Comment by bugs84** [comment]
Ok, I will use another http client for my case.
sorry for wasting your time with this invalid
