### ISSUE TITLE
FakeRequest doesn't allow to return different body depending on the url

### ISSUE THREAD

**Issue by dmzaytsev** [jcabi/jcabi-http#82]
FakeRequest doesn't allow to return different RequestBody depending on the url.
Needs to add new methods to FakeRequest
```
    public FakeRequest withBody(final String regexp, final String text) {
    }

    public FakeRequest withBody(final String regexp, final byte[] body) {
    } 
```

**Comment by dmzaytsev** [comment]
@yegor256 @dmarkov could you please assign this task to me?

**Comment by yegor256** [comment]
@dmarkov please assign @dmzaytsev to this task

**Comment by dmarkov** [comment]
@dmzaytsev this task will get someone's attention soon

**Comment by dmarkov** [comment]
@dmzaytsev thanks for the ticket, your account was topped for 15 mins, payment 55972701

**Comment by dmarkov** [comment]
> @dmarkov please assign @dmzaytsev to this task

@yegor256 OK @dmzaytsev please start, the task is yours

**Comment by dmzaytsev** [comment]
@dmarkov the PR here #83  please find someone to review. Thanks.

**Comment by dmzaytsev** [comment]
@dmarkov I am closing the task
[the reason:](https://github.com/jcabi/jcabi-http/pull/83#issuecomment-98603224)

>yegor256 commented an hour ago
@dmzaytsev I would just close it. no need to develop all this in jcabi-http if we have Takes

**Comment by dmarkov** [comment]
@dmzaytsev I added **30 mins** to your account, many thanks for working with the project! The completion time here was 56747190.. +30 to your rating, your total score is [+1182](http://www.netbout.com/b/35166?open=rating)
