### ISSUE TITLE
RequestBody.BaseBody.formParam append extra '&' at the end of last request parameter

### ISSUE THREAD

**Issue by super132** [jcabi/jcabi-http#85]
`RequestBody.BaseBody.formParam()` now always appends '&' at the end of every name-value pair of form parameters. However, there should be no '&' at the last name value pair. I would suggest to drop out the extra '&' when calling `back()` method.

**Comment by dmarkov** [comment]
@super132 I am aware of the task, give me some time to find a developer...

**Comment by dmarkov** [comment]
@super132 many thanks for the report, I topped your account for 15 mins, transaction AP-6NG1848522157064U

**Comment by dmarkov** [comment]
@yamstranger it's in your hands now, please proceed

**Comment by YamStranger** [comment]
@dmarkov I need more time to fix it

**Comment by dmarkov** [comment]
> @dmarkov I need more time to fix it

@yamstranger of course, take your time

**Comment by YamStranger** [comment]
@dmarkov fixed in #107. Close this issue please

**Comment by dmarkov** [comment]
> @dmarkov fixed in #107. Close this issue please

@yamstranger you should ask @super132 to close it, since he is the opener

**Comment by dmarkov** [comment]
@yamstranger Much appreciated! **30 mins** was added to your account, payment ID `64916008`, time spent is 2356 hours and 10 mins... added +30 to your rating, now it is equal to [-60](http://www.netbout.com/b/35267?open=rating)
