### ISSUE TITLE
Muti-part form for file upload

### ISSUE THREAD

**Issue by pinaf** [jcabi/jcabi-http#87]
It would be nice to extend the API with multi-part form for file uploading.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by dmarkov** [comment]
@pinaf thanks for reporting! I topped your account for 15 mins, transaction AP-0VR931824C1456809

**Comment by dmarkov** [comment]
@nikoladespotoski could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by NikolaDespotoski** [comment]
@dmarkov Assign someone else

**Comment by dmarkov** [comment]
@nikoladespotoski just a reminder that you're working with this task for 15 days already. -30 to your rating, your total score is [+280](http://www.netbout.com/b/36438?open=rating)

**Comment by NikolaDespotoski** [comment]
@yegor256 Points were deducted just after I asked to be assigned someone else.

**Comment by dmarkov** [comment]
> @dmarkov Assign someone else

@nikoladespotoski got it, someone else will be assigned soon

**Comment by dmarkov** [comment]
@amihaiemil the task is yours

**Comment by amihaiemil** [comment]
@pinaf Can you maybe give me a hint here? How would you start implementing this? The requirement seems a bit vaguely formulated to me :D

**Comment by pinaf** [comment]
@amihaiemil there is no multi-part document support currently. check out this answer for what I'd like to see http://stackoverflow.com/questions/8659808/how-does-http-file-upload-work
As to how it should be implemented, I have no idea :)

**Comment by amihaiemil** [comment]
@dmarkov I created PR #142 for this

**Comment by dmarkov** [comment]
> @dmarkov I created PR #142 for this

@amihaiemil thanks

**Comment by amihaiemil** [comment]
@dmarkov I need more time

**Comment by dmarkov** [comment]
> @dmarkov I need more time

@amihaiemil of course, take your time

**Comment by amihaiemil** [comment]
@pinaf the pr was merged. Can u close this? :)

**Comment by pinaf** [comment]
@amihaiemil thx!

**Comment by dmarkov** [comment]
@amihaiemil paid, thanks, added **30 mins** to your account, payment `AP-49K48919JG010304P`, 2543 hours and 39 mins was spent

+30 added to your rating, current score is: [+979](http://www.netbout.com/b/36402?open=rating)

**Comment by dmarkov** [comment]
@pinaf these 2 puzzles were created in this ticket: `87-5547b016`, `87-bd2cb401`/#150

**Comment by 0pdd** [comment]
@pinaf the puzzle [#163](https://github.com/jcabi/jcabi-http/issues/163) is still not solved; solved: [#164](https://github.com/jcabi/jcabi-http/issues/164).

**Comment by 0pdd** [comment]
@pinaf the puzzle [#333](https://github.com/jcabi/jcabi-http/issues/333) is still not solved.

**Comment by 0pdd** [comment]
@pinaf the puzzle [#unknown]() is still not solved; solved: [#333](https://github.com/jcabi/jcabi-http/issues/333).
