### ISSUE TITLE
ETag-based caching

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-http#89]
Similar to the existing but overly simple `CachingWire`, there ought to be another wire that implements caching based on the `ETag` response header and `If-None-Match` request header.

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by dmarkov** [comment]
@gmandnepr this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by gmandnepr** [comment]
@dmarkov pull request created https://github.com/jcabi/jcabi-http/pull/119

**Comment by dmarkov** [comment]
> @dmarkov pull request created https://github.com/jcabi/jcabi-http/pull/119

@gmandnepr OK

**Comment by gmandnepr** [comment]
@cvrebert pr is merged, please close the issue

**Comment by dmarkov** [comment]
@gmandnepr thank you, added **30 mins** to your acc, payment num is `75784902`, 193 hours and 26 mins spent in total to complete; +30 to your rating, your total score is [+0](http://www.netbout.com/b/36313?open=rating)
