### ISSUE TITLE
No timeouts

### ISSUE THREAD

**Issue by benhinssen** [jcabi/jcabi-http#91]
As far as I can see I can't specify a timeout on the connection.  Not with the JdkRequest or with the ApacheRequest.

I implemented timeouts in the following fork, but I have some trouble with qulice before I can submit a pull request:
https://github.com/benhinssen/jcabi-http/tree/timeouts

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@benhinssen thanks for the contribution! please, submit a pull request and we'll try to help you to make it suitable for qulice

**Comment by dmarkov** [comment]
@rultor rultor closed it (automatically), @benhinssen please take a look

**Comment by benhinssen** [comment]
@dmarkov Thanks, it was solved by the pull request #99.  I'll close the issue.
