### ISSUE TITLE
MkContainer should extend java.io.Closeable

### ISSUE THREAD

**Issue by cvrebert** [jcabi/jcabi-http#96]
That way, mock containers can be used in a [try-with-resources statement](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html), which should almost completely prevent accidental leakage of ports. Currently, users must always remember to call `.stop()` themselves at the end of tests. Human error means that this doesn't always happen. If we make it possible to use try-with-resources and reviewers enforce the usage of try-with-resources, then port leakage in tests should be prevented much more effectively.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by longtimeago** [comment]
@yegor256 it would be very useful to make MkContainer implement Closable

**Comment by longtimeago** [comment]
@dmarkov here is the PR https://github.com/jcabi/jcabi-http/pull/110

**Comment by longtimeago** [comment]
@cvrebert please, close the issue. It's done. Thanks!

**Comment by longtimeago** [comment]
@yegor256 please, release new version

**Comment by yegor256** [comment]
@rultor release, tag is `1.12`

**Comment by dmarkov** [comment]
> @dmarkov here is the PR https://github.com/jcabi/jcabi-http/pull/110

@longtimeago OK thanks, will take a look soon
