### ISSUE TITLE
Basic auth information logged by RetryWire

### ISSUE THREAD

**Issue by dominicfarr** [jcabi/jcabi-http#97]
When RetryWire fails, it logs a warning message that contains the the url, even if that url contains basic auth information used by BasicAuthWire.

I've had a quick look thought about having BasicAuthWire strip off the url credentials after the auth header is created so RetryWire doesn't have to worry about it. However, that would then put a ordering dependency on the Wires which isn't great.

Therefore, just hiding the credentials in the log statement in RetryWire seems a next best.

I'll arrange a pull request

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by andreoss** [comment]
`BasicAuthWire` can also strip user info from `home` after Auth header was added

**Comment by 0pdd** [comment]
@dominicfarr the puzzle [#215](https://github.com/jcabi/jcabi-http/issues/215) is still not solved.

**Comment by 0pdd** [comment]
@dominicfarr the only puzzle [#215](https://github.com/jcabi/jcabi-http/issues/215) is solved here.

**Comment by andreoss** [comment]
Closing as #215 is closed atm.
